create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 20),
  total integer not null check (total between 0 and 110),
  breakdown jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

create policy "public can insert scores"
on public.scores for insert
to anon
with check (char_length(name) between 1 and 20 and total between 0 and 110);

create policy "public can read rankings"
on public.scores for select
to anon
using (true);
